platform :ios, '9.0'
use_frameworks!

project '../../MapboxNavigation.xcodeproj'

def shared_pods
    pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :commit => 'ceaf58b780fc17ea44a9150041b602d017c1e567'
    pod 'OSRMTextInstructions', :path => '../../../osrm-text-instructions.swift'
    pod 'MapboxNavigation.swift', :path => '../../'
    pod 'MapboxNavigationUI.swift', :path => '../../'
    pod 'AWSPolly', '~> 2.5'
end

target 'Example-Swift' do
    shared_pods
end
